export const users = [
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "John",
			lastname: "Doe",
			username: "johndoe123",
			image: "https://www.example.com/images/johndoe.jpg",
			mail: "john.doe@example.com",
			password: "securePassword123",
			phone: "+15551234567",
			dob: "1990-01-15",
			address: {
				city: "New York",
				zipCode: "10001",
				street: "Main Street",
				streetNum: 123,
				numSupp: "A",
			},
		},
	},
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "Jane",
			lastname: "Smith",
			username: "janesmith456",
			image: "https://www.example.com/images/janesmith.png",
			mail: "jane.smith@example.com",
			password: "anotherSecurePassword",
			phone: "+447700900123",
			dob: "1985-06-22",
			address: {
				city: "London",
				zipCode: "SW1A 1AA",
				street: "Oxford Street",
				streetNum: 42,
				numSupp: "",
			},
		},
	},
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "Peter",
			lastname: "Jones",
			username: "peterjones789",
			mail: "peter.jones@example.com",
			password: "password12345",
			phone: "+4917612345678",
			dob: "1978-11-05",
			address: {
				city: "Berlin",
				zipCode: "10117",
				street: "Unter den Linden",
				streetNum: 78,
			},
		},
	},
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "Alice",
			lastname: "Johnson",
			username: "alicejohnson101",
			image: "https://www.example.com/images/alicejohnson.gif",
			mail: "alice.johnson@example.com",
			password: "veryStrongPassword",
			dob: "2000-03-10",
			address: {
				city: "Paris",
				zipCode: "75008",
				street: "Champs-Élysées",
				streetNum: 1,
			},
		},
	},
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "Bob",
			lastname: "Williams",
			username: "bobwilliams112",
			mail: "bob.williams@example.com",
			password: "bestPasswordEver",
			phone: "+331234567890",
			address: {
				city: "Tokyo",
				zipCode: "100-0005",
				street: "Ginza",
				streetNum: 555,
				numSupp: "B",
			},
		},
	},
];

export const companies = [
	{
		deleted: false,
		fitAdmin: "JohnDoe",
		name: "Acme Corporation",
		address: {
			street: "123 Main Street",
			city: "New York",
			state: "NY",
			country: "United States",
			zipCode: "12345",
		},
		phone: "+15551234567",
		email: "info@acmecorp.com",
		website: "https://www.acmecorp.com",
		logo: "https://www.acmecorp.com/logo.png",
		about: "Acme Corporation is a leading provider of widgets and gizmos.",
		openingHours: "Monday-Friday: 9am-5pm",
		numberOfPossibilities: 100,
		bookings: [],
		tasks: [],
	},
	{
		deleted: false,
		fitAdmin: "JaneSmith",
		name: "Smith & Sons",
		address: {
			street: "456 Elm Street",
			city: "London",
			country: "United Kingdom",
			zipCode: "SW1A 1AA",
		},
		phone: "+447700900123",
		email: "info@smithandsons.com",
		website: "https://www.smithandsons.com",
		logo: "https://www.smithandsons.com/logo.png",
		about: "Smith & Sons is a family-owned business that has been providing quality goods and services for over 100 years.",
		openingHours: "Monday-Saturday: 10am-6pm",
		numberOfPossibilities: 50,
		bookings: [],
		tasks: [],
	},
	{
		deleted: false,
		fitAdmin: "PeterJones",
		name: "Jones Enterprises",
		address: {
			street: "789 Oak Street",
			city: "Paris",
			country: "France",
			zipCode: "75008",
		},
		phone: "+331234567890",
		email: "info@jonesenterprises.com",
		website: "https://www.jonesenterprises.com",
		logo: "https://www.jonesenterprises.com/logo.png",
		about: "Jones Enterprises is a global leader in innovation and technology.",
		openingHours: "Monday-Friday: 8am-6pm, Saturday: 10am-2pm",
		numberOfPossibilities: 200,
		bookings: [],
		tasks: [],
	},
	{
		deleted: false,
		fitAdmin: "AliceJohnson",
		name: "Johnson & Johnson",
		address: {
			street: "1234 Maple Street",
			city: "Tokyo",
			country: "Japan",
			zipCode: "100-0005",
		},
		phone: "+81335551234",
		email: "info@johnsonandjohnson.com",
		website: "https://www.johnsonandjohnson.com",
		logo: "https://www.johnsonandjohnson.com/logo.png",
		about: "Johnson & Johnson is a diversified healthcare company that provides a wide range of products and services to consumers around the world.",
		openingHours: "Monday-Friday: 9am-6pm, Saturday: 10am-4pm",
		numberOfPossibilities: 150,
		bookings: [],
		tasks: [],
	},
	{
		deleted: false,
		fitAdmin: "BobWilliams",
		name: "Williams & Associates",
		address: {
			street: "567 Pine Street",
			city: "Berlin",
			country: "Germany",
			zipCode: "10117",
		},
		phone: "+4917612345678",
		email: "info@williamsandassociates.com",
		website: "https://www.williamsandassociates.com",
		logo: "https://www.williamsandassociates.com/logo.png",
		about: "Williams & Associates is a leading law firm specializing in corporate law and intellectual property.",
		openingHours: "Monday-Friday: 9am-5pm, Saturday: by appointment",
		numberOfPossibilities: 75,
		bookings: [],
		tasks: [],
	},
];

export const tasks = [
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Clean the windows",
		topic: "Cleaning",
		image: "https://www.example.com/images/cleanwindows.jpg",
		about: "Clean all the windows in the shop, inside and out.",
		timeRequired: 60,
		isFree: false,
		isDoneBefore: false,
		doneLast: "2023-12-20T10:00:00.000Z",
		costs: 25.0,
		neededMaterials: [
			{
				name: "Window cleaner",
				image: "https://www.example.com/images/windowcleaner.jpg",
				quantity: 1,
			},
			{
				name: "Microfiber cloth",
				image: "https://www.example.com/images/microfibercloth.jpg",
				quantity: 2,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Mop the floors",
		topic: "Cleaning",
		about: "Mop all the floors in the shop.",
		timeRequired: 30,
		isFree: false,
		isDoneBefore: true,
		costs: 15.0,
		neededMaterials: [
			{
				name: "Mop",
				quantity: 1,
			},
			{
				name: "Floor cleaner",
				quantity: 1,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopC",
		name: "Take out the trash",
		topic: "Cleaning",
		about: "Take out all the trash cans in the shop.",
		timeRequired: 15,
		isFree: true,
		isDoneBefore: false,
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopD",
		name: "Restock shelves",
		topic: "Inventory",
		about: "Restock all the shelves in the shop with new products.",
		timeRequired: 120,
		isFree: false,
		isDoneBefore: false,
		costs: 50.0,
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopE",
		name: "Organize stockroom",
		topic: "Inventory",
		about: "Organize the stockroom and put everything in its place.",
		timeRequired: 60,
		isFree: false,
		isDoneBefore: true,
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopF",
		name: "Count inventory",
		topic: "Inventory",
		about: "Count all the items in the inventory and record the quantities.",
		timeRequired: 180,
		isFree: false,
		isDoneBefore: false,
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopG",
		name: "Greet customers",
		topic: "Customer service",
		about: "Greet customers as they enter the shop and offer assistance.",
		timeRequired: 30,
		isFree: true,
		isDoneBefore: false,
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopH",
		name: "Answer customer questions",
		topic: "Customer service",
		about: "Answer customer questions about products and services.",
		timeRequired: 60,
		isFree: true,
		isDoneBefore: true,
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopI",
		name: "Process returns",
		topic: "Customer service",
		about: "Process customer returns and exchanges.",
		timeRequired: 30,
		isFree: true,
		isDoneBefore: false,
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopJ",
		name: "Create window display",
		topic: "Marketing",
		about: "Create an attractive window display to attract customers.",
		timeRequired: 120,
		isFree: false,
		isDoneBefore: false,
		slots_booked: {},
	},
];

export const cars = [
	{
		deleted: false,
		fitUser: [],
		licensePlate: "AB12345",
		lastNameOrCompany: "Doe",
		firstName: "John",
		address: "123 Main Street, Anytown",
		nextHU: "2024-05-10T12:00:00.000Z",
		dateOfFirstRegistration: "2020-01-15T12:00:00.000Z",
		manufacturerNumber: "M1234567890",
		typeNumber: "T9876543210",
		vehicleClass: "M1",
		FIN: "ABCDEFGHIJKLMNOPQ",
		checkDigit: 17,
		brand: "Ford",
		type: "Focus",
		variant: "Sedan",
		version: "Titanium",
		tasks: ["Oil change", "Tire rotation"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "CD56789",
		lastNameOrCompany: "Smith",
		firstName: "Jane",
		address: "456 Elm Street, Anytown",
		nextHU: "2023-11-22T12:00:00.000Z",
		dateOfFirstRegistration: "2018-06-22T12:00:00.000Z",
		manufacturerNumber: "M0987654321",
		typeNumber: "T1234567890",
		vehicleClass: "M1",
		FIN: "QRSTUVWXYZABCDEFG",
		checkDigit: 17,
		brand: "Volkswagen",
		type: "Golf",
		variant: "Hatchback",
		version: "Highline",
		tasks: ["Brake inspection", "Replace air filter"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "EF01234",
		lastNameOrCompany: "Jones",
		firstName: "Peter",
		address: "789 Oak Street, Anytown",
		nextHU: "2024-09-05T12:00:00.000Z",
		dateOfFirstRegistration: "2019-11-05T12:00:00.000Z",
		manufacturerNumber: "M2345678901",
		typeNumber: "T8765432109",
		vehicleClass: "N1",
		FIN: "HIJKLMNOPQRSTUVWXY",
		checkDigit: 17,
		brand: "Mercedes-Benz",
		type: "Sprinter",
		variant: "Van",
		version: "314 CDI",
		tasks: ["Check engine light", "Replace battery"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "GH45678",
		lastNameOrCompany: "Johnson",
		firstName: "Alice",
		address: "1011 Pine Street, Anytown",
		nextHU: "2025-03-10T12:00:00.000Z",
		dateOfFirstRegistration: "2021-03-10T12:00:00.000Z",
		manufacturerNumber: "M3456789012",
		typeNumber: "T7654321098",
		vehicleClass: "M1",
		FIN: "ZABCDEFGHIJKLMNOP",
		checkDigit: 17,
		brand: "BMW",
		type: "3 Series",
		variant: "Sedan",
		version: "320i",
		tasks: ["Wheel alignment", "Replace windshield wipers"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "IJ90123",
		lastNameOrCompany: "Williams",
		firstName: "Bob",
		address: "1213 Maple Street, Anytown",
		nextHU: "2023-07-15T12:00:00.000Z",
		dateOfFirstRegistration: "2017-07-15T12:00:00.000Z",
		manufacturerNumber: "M4567890123",
		typeNumber: "T6543210987",
		vehicleClass: "L1e-B",
		FIN: "QRSTUVWXYZABCDEFG",
		checkDigit: 17,
		brand: "Renault",
		type: "Zoe",
		variant: "Hatchback",
		version: "Intens",
		tasks: ["Software update", "Check charging port"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "KL34567",
		lastNameOrCompany: "Brown",
		firstName: "Charlie",
		address: "1415 Oak Street, Anytown",
		nextHU: "2024-12-20T12:00:00.000Z",
		dateOfFirstRegistration: "2022-12-20T12:00:00.000Z",
		manufacturerNumber: "M5678901234",
		typeNumber: "T5432109876",
		vehicleClass: "M1",
		FIN: "HIJKLMNOPQRSTUVWXY",
		checkDigit: 17,
		brand: "Audi",
		type: "A4",
		variant: "Avant",
		version: "40 TDI",
		tasks: ["Replace timing belt", "Check coolant level"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "MN89012",
		lastNameOrCompany: "Davis",
		firstName: "Emily",
		address: "1617 Pine Street, Anytown",
		nextHU: "2023-06-05T12:00:00.000Z",
		dateOfFirstRegistration: "2016-06-05T12:00:00.000Z",
		manufacturerNumber: "M6789012345",
		typeNumber: "T4321098765",
		vehicleClass: "M1",
		FIN: "ZABCDEFGHIJKLMNOP",
		checkDigit: 17,
		brand: "Tesla",
		type: "Model 3",
		variant: "Long Range",
		version: "Performance",
		tasks: ["Calibrate cameras", "Rotate tires"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "OP23456",
		lastNameOrCompany: "Wilson",
		firstName: "George",
		address: "1819 Maple Street, Anytown",
		nextHU: "2024-10-10T12:00:00.000Z",
		dateOfFirstRegistration: "2020-10-10T12:00:00.000Z",
		manufacturerNumber: "M7890123456",
		typeNumber: "T3210987654",
		vehicleClass: "M1",
		FIN: "QRSTUVWXYZABCDEFG",
		checkDigit: 17,
		brand: "Hyundai",
		type: "Tucson",
		variant: "SUV",
		version: "N Line",
		tasks: ["Check brake pads", "Replace oil filter"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "QR78901",
		lastNameOrCompany: "Garcia",
		firstName: "Harry",
		address: "2021 Oak Street, Anytown",
		nextHU: "2023-04-22T12:00:00.000Z",
		dateOfFirstRegistration: "2018-04-22T12:00:00.000Z",
		manufacturerNumber: "M8901234567",
		typeNumber: "T2109876543",
		vehicleClass: "L3e-A1",
		FIN: "HIJKLMNOPQRSTUVWXY",
		checkDigit: 17,
		brand: "BMW",
		type: "C 400 GT",
		variant: "Scooter",
		version: "",
		tasks: ["Service engine", "Replace tires"],
	},
	{
		deleted: false,
		fitUser: [],
		licensePlate: "ST12345",
		lastNameOrCompany: "Rodriguez",
		firstName: "Isabelle",
		address: "2223 Pine Street, Anytown",
		nextHU: "2024-08-05T12:00:00.000Z",
		dateOfFirstRegistration: "2019-08-05T12:00:00.000Z",
		manufacturerNumber: "M9012345678",
		typeNumber: "T1098765432",
		vehicleClass: "M1",
		FIN: "ZABCDEFGHIJKLMNOP",
		checkDigit: 17,
		brand: "Kia",
		type: "Sportage",
		variant: "SUV",
		version: "GT Line",
		tasks: ["Check air conditioning", "Replace cabin filter"],
	},
];
