export const users = [
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "John",
			lastname: "Doe",
			username: "johndoe123",
			image: "https://www.example.com/images/johndoe.jpg",
			mail: "john.doe@example.com",
			password: "securePassword123",
			phone: "+15551234567",
			dob: "1990-01-15",
			address: {
				city: "New York",
				zipCode: "10001",
				street: "Main Street",
				streetNum: 123,
				numSupp: "A",
			},
		},
	},
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "Jane",
			lastname: "Smith",
			username: "janesmith456",
			image: "https://www.example.com/images/janesmith.png",
			mail: "jane.smith@example.com",
			password: "anotherSecurePassword",
			phone: "+447700900123",
			dob: "1985-06-22",
			address: {
				city: "London",
				zipCode: "SW1A 1AA",
				street: "Oxford Street",
				streetNum: 42,
				numSupp: "",
			},
		},
	},
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "Peter",
			lastname: "Jones",
			username: "peterjones789",
			mail: "peter.jones@example.com",
			password: "password12345",
			phone: "+4917612345678",
			dob: "1978-11-05",
			address: {
				city: "Berlin",
				zipCode: "10117",
				street: "Unter den Linden",
				streetNum: 78,
			},
		},
	},
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "Alice",
			lastname: "Johnson",
			username: "alicejohnson101",
			image: "https://www.example.com/images/alicejohnson.gif",
			mail: "alice.johnson@example.com",
			password: "veryStrongPassword",
			dob: "2000-03-10",
			address: {
				city: "Paris",
				zipCode: "75008",
				street: "Champs-Élysées",
				streetNum: 1,
			},
		},
	},
	{
		deleted: false,
		role: "user",
		person: {
			firstname: "Bob",
			lastname: "Williams",
			username: "bobwilliams112",
			mail: "bob.williams@example.com",
			password: "bestPasswordEver",
			phone: "+331234567890",
			address: {
				city: "Tokyo",
				zipCode: "100-0005",
				street: "Ginza",
				streetNum: 555,
				numSupp: "B",
			},
		},
	},
];

export const companies = [
	{
		deleted: false,
		fitAdmin: "JohnDoe",
		name: "Acme Corporation",
		address: {
			street: "123 Main Street",
			city: "New York",
			state: "NY",
			country: "United States",
			zipCode: "12345",
		},
		phone: "+15551234567",
		email: "info@acmecorp.com",
		website: "https://www.acmecorp.com",
		logo: "https://www.acmecorp.com/logo.png",
		about: "Acme Corporation is a leading provider of widgets and gizmos.",
		openingHours: "Monday-Friday: 9am-5pm",
		numberOfPossibilities: 100,
		bookings: [],
		tasks: [],
	},
	{
		deleted: false,
		fitAdmin: "JaneSmith",
		name: "Smith & Sons",
		address: {
			street: "456 Elm Street",
			city: "London",
			country: "United Kingdom",
			zipCode: "SW1A 1AA",
		},
		phone: "+447700900123",
		email: "info@smithandsons.com",
		website: "https://www.smithandsons.com",
		logo: "https://www.smithandsons.com/logo.png",
		about: "Smith & Sons is a family-owned business that has been providing quality goods and services for over 100 years.",
		openingHours: "Monday-Saturday: 10am-6pm",
		numberOfPossibilities: 50,
		bookings: [],
		tasks: [],
	},
	{
		deleted: false,
		fitAdmin: "PeterJones",
		name: "Jones Enterprises",
		address: {
			street: "789 Oak Street",
			city: "Paris",
			country: "France",
			zipCode: "75008",
		},
		phone: "+331234567890",
		email: "info@jonesenterprises.com",
		website: "https://www.jonesenterprises.com",
		logo: "https://www.jonesenterprises.com/logo.png",
		about: "Jones Enterprises is a global leader in innovation and technology.",
		openingHours: "Monday-Friday: 8am-6pm, Saturday: 10am-2pm",
		numberOfPossibilities: 200,
		bookings: [],
		tasks: [],
	},
	{
		deleted: false,
		fitAdmin: "AliceJohnson",
		name: "Johnson & Johnson",
		address: {
			street: "1234 Maple Street",
			city: "Tokyo",
			country: "Japan",
			zipCode: "100-0005",
		},
		phone: "+81335551234",
		email: "info@johnsonandjohnson.com",
		website: "https://www.johnsonandjohnson.com",
		logo: "https://www.johnsonandjohnson.com/logo.png",
		about: "Johnson & Johnson is a diversified healthcare company that provides a wide range of products and services to consumers around the world.",
		openingHours: "Monday-Friday: 9am-6pm, Saturday: 10am-4pm",
		numberOfPossibilities: 150,
		bookings: [],
		tasks: [],
	},
	{
		deleted: false,
		fitAdmin: "BobWilliams",
		name: "Williams & Associates",
		address: {
			street: "567 Pine Street",
			city: "Berlin",
			country: "Germany",
			zipCode: "10117",
		},
		phone: "+4917612345678",
		email: "info@williamsandassociates.com",
		website: "https://www.williamsandassociates.com",
		logo: "https://www.williamsandassociates.com/logo.png",
		about: "Williams & Associates is a leading law firm specializing in corporate law and intellectual property.",
		openingHours: "Monday-Friday: 9am-5pm, Saturday: by appointment",
		numberOfPossibilities: 75,
		bookings: [],
		tasks: [],
	},
];

export const tasks = [
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Replace Spark Plugs",
		topic: "Engine Repair",
		image: "https://www.example.com/images/sparkplugs.jpg",
		about: "Remove old spark plugs and install new ones with proper gap.",
		timeRequired: 60,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-12-10T11:00:00.000Z",
		costs: 70.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Replace Timing Belt",
		topic: "Engine Repair",
		image: "https://www.example.com/images/timingbelt.jpg",
		about: "Remove old timing belt and install new one, ensuring proper alignment.",
		timeRequired: 180,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 300.0,
		neededMaterials: [
			{
				name: "Timing Belt Kit",
				image: "https://www.example.com/images/timingbeltkit.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Head Gasket Replacement",
		topic: "Engine Repair",
		image: "https://www.example.com/images/headgasket.jpg",
		about: "Replace blown head gasket, including cleaning and resurfacing the cylinder head.",
		timeRequired: 360,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 800.0,
		neededMaterials: [
			{
				name: "Head Gasket Set",
				image: "https://www.example.com/images/headgasketset.jpg",
				quantity: 99,
			},
			{
				name: "Head Bolts",
				image: "https://www.example.com/images/headbolts.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Engine Diagnostics",
		topic: "Engine Repair",
		image: "https://www.example.com/images/enginediagnostics.jpg",
		about: "Run diagnostic tests to identify engine problems and trouble codes.",
		timeRequired: 30,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2024-01-10T08:30:00.000Z",
		costs: 50.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Fuel Injector Cleaning",
		topic: "Engine Repair",
		image: "https://www.example.com/images/fuelinjector.jpg",
		about: "Clean fuel injectors to improve engine performance and fuel efficiency.",
		timeRequired: 90,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 150.0,
		neededMaterials: [
			{
				name: "Fuel Injector Cleaner",
				image: "https://www.example.com/images/fuelinjectorcleaner.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Replace Brake Pads",
		topic: "Brakes",
		image: "https://www.example.com/images/brakepads.jpg",
		about: "Replace worn-out brake pads on all four wheels.",
		timeRequired: 90,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 120.0,
		neededMaterials: [
			{
				name: "Brake Pads",
				image: "https://www.example.com/images/brakepads.jpg",
				quantity: 99,
			},
			{
				name: "Brake Cleaner",
				image: "https://www.example.com/images/brakecleaner.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Resurface Brake Rotors",
		topic: "Brakes",
		image: "https://www.example.com/images/brakerotors.jpg",
		about: "Smooth out warped or worn brake rotors to ensure proper braking.",
		timeRequired: 60,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-11-20T10:30:00.000Z",
		costs: 80.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Replace Brake Calipers",
		topic: "Brakes",
		image: "https://www.example.com/images/brakecalipers.jpg",
		about: "Replace faulty brake calipers to restore proper braking function.",
		timeRequired: 120,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 200.0,
		neededMaterials: [
			{
				name: "Brake Calipers",
				image: "https://www.example.com/images/brakecalipers.jpg",
				quantity: 99,
			},
			{
				name: "Brake Fluid",
				image: "https://www.example.com/images/brakefluid.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Bleed Brake System",
		topic: "Brakes",
		image: "https://www.example.com/images/bleedbrakes.jpg",
		about: "Remove air from the brake lines to ensure optimal braking performance.",
		timeRequired: 45,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2024-01-02T15:00:00.000Z",
		costs: 60.0,
		neededMaterials: [
			{
				name: "Brake Fluid",
				image: "https://www.example.com/images/brakefluid.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Inspect Brake Lines",
		topic: "Brakes",
		image: "https://www.example.com/images/brakelines.jpg",
		about: "Thoroughly check brake lines for leaks, damage, or wear.",
		timeRequired: 30,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-12-28T09:00:00.000Z",
		costs: 40.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Wheel Alignment",
		topic: "Steering & Suspension",
		image: "https://www.example.com/images/wheelalignment.jpg",
		about: "Adjust wheel angles to ensure proper vehicle handling and tire wear.",
		timeRequired: 60,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-11-05T14:00:00.000Z",
		costs: 100.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Replace Shocks & Struts",
		topic: "Steering & Suspension",
		image: "https://www.example.com/images/shockstruts.jpg",
		about: "Replace worn-out shocks and struts to improve ride comfort and handling.",
		timeRequired: 120,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 250.0,
		neededMaterials: [
			{
				name: "Shocks & Struts",
				image: "https://www.example.com/images/shockstruts.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Replace Tie Rod Ends",
		topic: "Steering & Suspension",
		image: "https://www.example.com/images/tierodends.jpg",
		about: "Replace worn tie rod ends to maintain steering control and prevent tire wear.",
		timeRequired: 90,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 180.0,
		neededMaterials: [
			{
				name: "Tie Rod Ends",
				image: "https://www.example.com/images/tierodends.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Steering Rack Inspection",
		topic: "Steering & Suspension",
		image: "https://www.example.com/images/steeringrack.jpg",
		about: "Inspect the steering rack for leaks, damage, and proper function.",
		timeRequired: 30,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-12-15T10:00:00.000Z",
		costs: 40.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Suspension System Check",
		topic: "Steering & Suspension",
		image: "https://www.example.com/images/suspensionsystem.jpg",
		about: "Comprehensive inspection of the entire suspension system for wear and tear.",
		timeRequired: 45,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2024-01-08T16:30:00.000Z",
		costs: 60.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Replace Air Filter",
		topic: "Maintenance",
		image: "https://www.example.com/images/airfilter.jpg",
		about: "Replace the engine air filter to ensure proper airflow and engine performance.",
		timeRequired: 15,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-12-05T09:30:00.000Z",
		costs: 30.0,
		neededMaterials: [
			{
				name: "Air Filter",
				image: "https://www.example.com/images/airfilter.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Replace Cabin Air Filter",
		topic: "Maintenance",
		image: "https://www.example.com/images/cabinfilter.jpg",
		about: "Replace the cabin air filter to improve air quality inside the vehicle.",
		timeRequired: 20,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-11-10T11:00:00.000Z",
		costs: 40.0,
		neededMaterials: [
			{
				name: "Cabin Air Filter",
				image: "https://www.example.com/images/cabinfilter.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Fluid Top-Off",
		topic: "Maintenance",
		image: "https://www.example.com/images/fluidtopoff.jpg",
		about: "Check and top off essential fluids like coolant, brake fluid, and power steering fluid.",
		timeRequired: 15,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2024-01-15T14:30:00.000Z",
		costs: 20.0,
		neededMaterials: [
			{
				name: "Coolant",
				image: "https://www.example.com/images/coolant.jpg",
				quantity: 99,
			},
			{
				name: "Brake Fluid",
				image: "https://www.example.com/images/brakefluid.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Wiper Blade Replacement",
		topic: "Maintenance",
		image: "https://www.example.com/images/wiperblades.jpg",
		about: "Replace worn-out wiper blades for optimal visibility in all weather conditions.",
		timeRequired: 10,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-12-20T10:00:00.000Z",
		costs: 25.0,
		neededMaterials: [
			{
				name: "Wiper Blades",
				image: "https://www.example.com/images/wiperblades.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Battery Check",
		topic: "Maintenance",
		image: "https://www.example.com/images/batterycheck.jpg",
		about: "Test battery health and charging system to ensure reliable starting.",
		timeRequired: 10,
		isFree: true,
		isDoneBefore: true,
		doneLast: "2024-01-05T16:00:00.000Z",
		costs: 0.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopB",
		name: "Diagnostic Scan",
		topic: "Diagnostics",
		image: "https://www.example.com/images/diagnosticscan.jpg",
		about: "Perform a comprehensive diagnostic scan to identify any vehicle issues.",
		timeRequired: 30,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2024-01-12T10:30:00.000Z",
		costs: 50.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
	{
		deleted: false,
		fitShop: "ShopA",
		name: "Check Engine Light Diagnostics",
		topic: "Diagnostics",
		image: "https://www.example.com/images/checkenginelight.jpg",
		about: "Diagnose the cause of a check engine light and provide solutions.",
		timeRequired: 45,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 70.0,
		neededMaterials: [
			{
				name: "Spark Plugs",
				image: "https://www.example.com/images/sparkplugs.jpg",
				quantity: 99,
			},
			{
				name: "Gap Tool",
				image: "https://www.example.com/images/gaptool.jpg",
				quantity: 99,
			},
		],
		slots_booked: {},
	},
];
