export const users = [
	{
		person: {
			firstname: "Emma",
			lastname: "Schmidt",
			username: "emmaschmidt",
			image: "https://example.com/avatars/emma.jpg",
			mail: "emma.schmidt@example.com",
			password: "hashedpassword123",
			phone: 1234567890,
			adress: {
				city: "Berlin",
				zipCode: 10115,
				street: "Friedrichstraße",
				streetNum: 123,
				numSupp: "A",
			},
			dob: "1990-05-15T00:00:00.000Z",
		},
		cars: [],
		bookings: [],
	},
	{
		person: {
			firstname: "Max",
			lastname: "Müller",
			username: "maxmueller",
			image: "https://example.com/avatars/max.jpg",
			mail: "max.mueller@example.com",
			password: "hashedpassword456",
			phone: 9876543210,
			adress: {
				city: "Munich",
				zipCode: 80331,
				street: "Marienplatz",
				streetNum: 8,
				numSupp: null,
			},
			dob: "1985-08-22T00:00:00.000Z",
		},
		cars: [],
		bookings: [],
	},
	{
		person: {
			firstname: "Anna",
			lastname: "Weber",
			username: "annaweber",
			image: "https://example.com/avatars/anna.jpg",
			mail: "anna.weber@example.com",
			password: "hashedpassword789",
			phone: 1122334455,
			adress: {
				city: "Hamburg",
				zipCode: 20095,
				street: "Rathausmarkt",
				streetNum: 1,
				numSupp: null,
			},
			dob: "1988-11-30T00:00:00.000Z",
		},
		cars: [],
		bookings: [],
	},
	{
		person: {
			firstname: "Felix",
			lastname: "Bauer",
			username: "felixbauer",
			image: "https://example.com/avatars/felix.jpg",
			mail: "felix.bauer@example.com",
			password: "hashedpassword101",
			phone: 5566778899,
			adress: {
				city: "Frankfurt",
				zipCode: 60313,
				street: "Römerberg",
				streetNum: 23,
				numSupp: "B",
			},
			dob: "1992-03-10T00:00:00.000Z",
		},
		cars: [],
		bookings: [],
	},
	{
		person: {
			firstname: "Sophie",
			lastname: "Fischer",
			username: "sophiefischer",
			image: "https://example.com/avatars/sophie.jpg",
			mail: "sophie.fischer@example.com",
			password: "hashedpassword202",
			phone: 3344556677,
			adress: {
				city: "Cologne",
				zipCode: 50667,
				street: "Alter Markt",
				streetNum: 55,
				numSupp: null,
			},
			dob: "1987-09-05T00:00:00.000Z",
		},
		cars: [],
		bookings: [],
	},
];

export const admins = [
	{
		person: {
			firstname: "Admin",
			lastname: "One",
			username: "adminone",
			image: "https://example.com/avatars/admin1.jpg",
			mail: "admin.one@example.com",
			password: "hashedadminpass1",
			phone: 1111111111,
			adress: {
				city: "Berlin",
				zipCode: 10117,
				street: "Unter den Linden",
				streetNum: 77,
				numSupp: null,
			},
			dob: "1980-01-01T00:00:00.000Z",
		},
		company: {
			name: "AutoCare Berlin GmbH",
			adress: {
				city: "Berlin",
				zipCode: 10117,
				street: "Friedrichstraße",
				streetNum: 100,
				numSupp: null,
			},
			phone: 3012345678,
			mail: "info@autocare-berlin.de",
			website: "https://www.autocare-berlin.de",
			logo: "https://example.com/logos/autocare-berlin.png",
			about: "Your trusted partner for all automotive needs in Berlin",
			openingHours: "Mon-Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 2:00 PM",
			numberOfPossibilities: 10,
			bookings: [],
			tasks: [],
		},
	},
	{
		person: {
			firstname: "Admin",
			lastname: "Two",
			username: "admintwo",
			image: "https://example.com/avatars/admin2.jpg",
			mail: "admin.two@example.com",
			password: "hashedadminpass2",
			phone: 2222222222,
			adress: {
				city: "Munich",
				zipCode: 80333,
				street: "Leopoldstraße",
				streetNum: 50,
				numSupp: null,
			},
			dob: "1982-02-02T00:00:00.000Z",
		},
		company: {
			name: "AutoCare Munich GmbH",
			adress: {
				city: "Munich",
				zipCode: 80333,
				street: "Ludwigstraße",
				streetNum: 25,
				numSupp: null,
			},
			phone: 8912345678,
			mail: "info@autocare-munich.de",
			website: "https://www.autocare-munich.de",
			logo: "https://example.com/logos/autocare-munich.png",
			about: "Premier automotive service in Munich",
			openingHours: "Mon-Fri: 7:30 AM - 7:00 PM, Sat: 9:00 AM - 3:00 PM",
			numberOfPossibilities: 8,
			bookings: [],
			tasks: [],
		},
	},
	{
		person: {
			firstname: "Admin",
			lastname: "Three",
			username: "adminthree",
			image: "https://example.com/avatars/admin3.jpg",
			mail: "admin.three@example.com",
			password: "hashedadminpass3",
			phone: 3333333333,
			adress: {
				city: "Hamburg",
				zipCode: 20095,
				street: "Mönckebergstraße",
				streetNum: 30,
				numSupp: null,
			},
			dob: "1983-03-03T00:00:00.000Z",
		},
		company: {
			name: "AutoCare Hamburg GmbH",
			adress: {
				city: "Hamburg",
				zipCode: 20095,
				street: "Ballindamm",
				streetNum: 40,
				numSupp: null,
			},
			phone: 4012345678,
			mail: "info@autocare-hamburg.de",
			website: "https://www.autocare-hamburg.de",
			logo: "https://example.com/logos/autocare-hamburg.png",
			about: "Hamburg's finest automotive care center",
			openingHours: "Mon-Fri: 8:00 AM - 6:30 PM, Sat: 9:00 AM - 2:30 PM",
			numberOfPossibilities: 12,
			bookings: [],
			tasks: [],
		},
	},
	{
		person: {
			firstname: "Admin",
			lastname: "Four",
			username: "adminfour",
			image: "https://example.com/avatars/admin4.jpg",
			mail: "admin.four@example.com",
			password: "hashedadminpass4",
			phone: 4444444444,
			adress: {
				city: "Frankfurt",
				zipCode: 60311,
				street: "Zeil",
				streetNum: 85,
				numSupp: null,
			},
			dob: "1984-04-04T00:00:00.000Z",
		},
		company: {
			name: "AutoCare Frankfurt GmbH",
			adress: {
				city: "Frankfurt",
				zipCode: 60311,
				street: "Mainzer Landstraße",
				streetNum: 60,
				numSupp: null,
			},
			phone: 6912345678,
			mail: "info@autocare-frankfurt.de",
			website: "https://www.autocare-frankfurt.de",
			logo: "https://example.com/logos/autocare-frankfurt.png",
			about: "Top-notch automotive services in Frankfurt",
			openingHours: "Mon-Fri: 7:00 AM - 7:00 PM, Sat: 8:00 AM - 4:00 PM",
			numberOfPossibilities: 15,
			bookings: [],
			tasks: [],
		},
	},
	{
		person: {
			firstname: "Admin",
			lastname: "Five",
			username: "adminfive",
			image: "https://example.com/avatars/admin5.jpg",
			mail: "admin.five@example.com",
			password: "hashedadminpass5",
			phone: 5555555555,
			adress: {
				city: "Cologne",
				zipCode: 50667,
				street: "Hohe Straße",
				streetNum: 120,
				numSupp: null,
			},
			dob: "1985-05-05T00:00:00.000Z",
		},
		company: {
			name: "AutoCare Cologne GmbH",
			adress: {
				city: "Cologne",
				zipCode: 50667,
				street: "Rheinauhafen",
				streetNum: 15,
				numSupp: null,
			},
			phone: 22112345678,
			mail: "info@autocare-cologne.de",
			website: "https://www.autocare-cologne.de",
			logo: "https://example.com/logos/autocare-cologne.png",
			about: "Cologne's most reliable automotive service center",
			openingHours: "Mon-Fri: 8:30 AM - 6:30 PM, Sat: 9:30 AM - 3:30 PM",
			numberOfPossibilities: 9,
			bookings: [],
			tasks: [],
		},
	},
];

export const cars = [
	{
		licensePlate: "B-AB 1234",
		lastNameOrCompany: "Schmidt",
		firstName: "Emma",
		adress: "Friedrichstraße 123, 10115 Berlin",
		nextHU: "2024-06-30T00:00:00.000Z",
		dateOfFirstRegistration: "2018-03-15T00:00:00.000Z",
		manufacturerNumber: "WBA1234567",
		typeNumber: "X123456",
		vehicleClass: "Passenger Car",
		FIN: "WBAXXX0000XXX1234",
		checkDigit: 7,
		make: "BMW",
		type: "3 Series",
		variant: "Sedan",
		version: "320i",
		tasks: [],
	},
	{
		licensePlate: "M-CD 5678",
		lastNameOrCompany: "Müller",
		firstName: "Max",
		adress: "Marienplatz 8, 80331 Munich",
		nextHU: "2023-12-31T00:00:00.000Z",
		dateOfFirstRegistration: "2020-01-10T00:00:00.000Z",
		manufacturerNumber: "WDD1234567",
		typeNumber: "Y789012",
		vehicleClass: "Passenger Car",
		FIN: "WDDXXX0000XXX5678",
		checkDigit: 3,
		make: "Mercedes-Benz",
		type: "C-Class",
		variant: "Sedan",
		version: "C200",
		tasks: [],
	},
	{
		licensePlate: "HH-EF 9012",
		lastNameOrCompany: "Weber",
		firstName: "Anna",
		adress: "Rathausmarkt 1, 20095 Hamburg",
		nextHU: "2024-09-30T00:00:00.000Z",
		dateOfFirstRegistration: "2019-07-22T00:00:00.000Z",
		manufacturerNumber: "WAU2345678",
		typeNumber: "Z345678",
		vehicleClass: "Passenger Car",
		FIN: "WAUXXX0000XXX9012",
		checkDigit: 5,
		make: "Audi",
		type: "A4",
		variant: "Avant",
		version: "40 TDI",
		tasks: [],
	},
	{
		licensePlate: "F-GH 3456",
		lastNameOrCompany: "Bauer",
		firstName: "Felix",
		adress: "Römerberg 23, 60313 Frankfurt",
		nextHU: "2025-03-31T00:00:00.000Z",
		dateOfFirstRegistration: "2021-11-05T00:00:00.000Z",
		manufacturerNumber: "WVW3456789",
		typeNumber: "A901234",
		vehicleClass: "Passenger Car",
		FIN: "WVWXXX0000XXX3456",
		checkDigit: 9,
		make: "Volkswagen",
		type: "Golf",
		variant: "Hatchback",
		version: "1.5 TSI",
		tasks: [],
	},
	{
		licensePlate: "K-IJ 7890",
		lastNameOrCompany: "Fischer",
		firstName: "Sophie",
		adress: "Alter Markt 55, 50667 Cologne",
		nextHU: "2024-11-30T00:00:00.000Z",
		dateOfFirstRegistration: "2017-09-18T00:00:00.000Z",
		manufacturerNumber: "W0L4567890",
		typeNumber: "B567890",
		vehicleClass: "Passenger Car",
		FIN: "W0LXXX0000XXX7890",
		checkDigit: 1,
		make: "Opel",
		type: "Astra",
		variant: "Sports Tourer",
		version: "1.2 Turbo",
		tasks: [],
	},
];

export const tasks = [
	{
		name: "Oil Change",
		topic: "Maintenance",
		image: "https://example.com/services/oil-change.jpg",
		about: "Regular oil changes to keep your engine running smoothly",
		timeRequired: 60,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-05-15T00:00:00.000Z",
		costs: 79.99,
		neededMaterialsdoneLast: "2023-05-15T00:00:00.000Z",
		costs: 79.99,
		neededMaterials: [
			{
				name: "Engine Oil",
				image: "https://example.com/materials/engine-oil.jpg",
				quantity: 5,
			},
			{
				name: "Oil Filter",
				image: "https://example.com/materials/oil-filter.jpg",
				quantity: 1,
			},
		],
		slots_booked: {},
	},
	{
		name: "Tire Rotation",
		topic: "Maintenance",
		image: "https://example.com/services/tire-rotation.jpg",
		about: "Rotate your tires to ensure even wear and extend their life",
		timeRequired: 45,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2023-04-01T00:00:00.000Z",
		costs: 49.99,
		neededMaterials: [],
		slots_booked: {},
	},
	{
		name: "Brake Inspection",
		topic: "Safety",
		image: "https://example.com/services/brake-inspection.jpg",
		about: "Comprehensive brake system check for your safety",
		timeRequired: 30,
		isFree: true,
		isDoneBefore: false,
		doneLast: null,
		costs: 0,
		neededMaterials: [],
		slots_booked: {},
	},
	{
		name: "Air Conditioning Service",
		topic: "Comfort",
		image: "https://example.com/services/ac-service.jpg",
		about: "Ensure your car's AC system is working efficiently",
		timeRequired: 90,
		isFree: false,
		isDoneBefore: true,
		doneLast: "2022-06-10T00:00:00.000Z",
		costs: 129.99,
		neededMaterials: [
			{
				name: "Refrigerant",
				image: "https://example.com/materials/refrigerant.jpg",
				quantity: 1,
			},
		],
		slots_booked: {},
	},
	{
		name: "Battery Replacement",
		topic: "Electrical",
		image: "https://example.com/services/battery-replacement.jpg",
		about: "Replace your old battery with a new one",
		timeRequired: 30,
		isFree: false,
		isDoneBefore: false,
		doneLast: null,
		costs: 159.99,
		neededMaterials: [
			{
				name: "Car Battery",
				image: "https://example.com/materials/car-battery.jpg",
				quantity: 1,
			},
		],
		slots_booked: {},
	},
];

export default { users, admins, cars, tasks };
